name: 强皓桐的兴趣课题组 Qianghaotong's Interest Research Group
url: https://qianghaotong.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# 使用 Pygments 模块对代码片段进行语法高亮
highlighter: pygments

# 博客文章的路径结构
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8

# “人员”页面的角色分类
roles:
  - key: highschool
    name: 高中阶段 High School Stage
  - key: ugrad
    name: 本科阶段 Undergraduate Stage
  - key: grad
    name: 研究生 Graduate Stage
  - key: future
    name: 未来发展 Future Development

# 主页显示的新闻条目数量
front_page_news: 8

# 链接的基本路径名
base: ''

# 为 _projects 文件夹中的内容生成页面
collections:
  projects:
    output: true

# 导航栏链接
navigation:
  - title: 兴趣 Interests
    link: /
  - title: 喜好 Preferences
    link: /preferences.html
  - title: 能力 Abilities
    link: /abilities.html
    link: /research.html
  - title: 论文 Publications
    link: /publications.html
